template: Hello, %s!
defaultName: Stranger

server:
  rootPath: '/api/*'
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 9090

swagger:
  resourcePackage: de.cranix.api.resources
  title: Open School Server API
  version: 0.0.1

logging:
  level: INFO
  loggers:
    de.cranix: DEBUG
    io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper: DEBUG
#    org.glassfish.jersey.logging.ServerLoggingFilter: DEBUG
#    org.glassfish.jersey.logging.LoggingFeature: DEBUG
